### ISSUE TITLE
not possible to use the mod 

### ISSUE THREAD

**Issue by 4Jashin** [SongXia-NYU/nuclear_craft#20]
i added the mod today on the lastest version and i get this error message and no idea how to fix it (sorry if its not the good place i litteraly made an account here to ask for help)  
![image](https://user-images.githubusercontent.com/89281469/130301481-7d632358-5343-46a4-9545-02256aff6ddc.png)

thanks in advance

**Comment by SongXia-NYU** [comment]
Thank you for reporting this bug!
Please tell me the version you are using and the crash report (located in .mincraft folder)

**Comment by 4Jashin** [comment]
![image](https://user-images.githubusercontent.com/89281469/130323818-b6ef83c6-1a69-4e88-84cc-cbc5c6378a3d.png)
[crash-2021-08-21_04.23.54-fml.txt](https://github.com/SongXia-NYU/nuclear_craft/files/7025614/crash-2021-08-21_04.23.54-fml.txt)

this is what i understand you are asking me if im wrong please add more detail to what you need

**Comment by SongXia-NYU** [comment]
Thank you for reporting this. Fixed in 0.9.5.
