### ISSUE TITLE
Guns, Rockets, and Atomic Explosions - Mouse Sensitivity Bug

### ISSUE THREAD

**Issue by ZephyrusTech** [SongXia-NYU/nuclear_craft#7]
I have been working on a modpack and a friend who was testing it kept complaining that he couldn't change his mouse sensitivity. I went through all the mods and disabled one at a time until I figured out that this mod was causing the issue. I load into game and go to Controls -> Mouse Settings and change the sensitivity bar to a different amount. Then I save and close the options and nothing changes. I go back to Mouse Settings and it is magically back to 100% default. I have not tested if there is still issue when I have this mod alone without others -- so could be conflict with other mods.

Minecraft version: 1.16.3
Forge version: 34.1.35
Mod Version: nuclear_craft-1.16.3-0.5.0

**Comment by SongXia-NYU** [comment]
Thank you for reporting this.
Fixed in 0.5.1
